M48
; DRILL file {KiCad 9.0.0-9.0.0-2~ubuntu24.04.1} date 2025-04-06T07:03:20+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-06T07:03:20+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-9.0.0-2~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X162.625Y-73.86
T2
X162.625Y-98.86
M30
